# Generated by Django 6.0.4 on 2026-05-20 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthIntakeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("problem_name", models.CharField(blank=True, max_length=120)),
                ("intake_summary", models.TextField(blank=True)),
                ("dashboard_values", models.JSONField(blank=True, default=dict)),
                ("reminders", models.JSONField(blank=True, default=list)),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("pdf_file", models.FileField(blank=True, upload_to="health_reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="emailotp",
            new_name="accounts_em_email_c46531_idx",
            old_name="accounts_em_email_2e8ec9_idx",
        ),
        migrations.AddField(
            model_name="healthintakereport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
