# Generated by Django 6.0.4 on 2026-05-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_healthintakereport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthintakereport",
            name="html_file",
            field=models.FileField(blank=True, upload_to="health_reports/html/"),
        ),
    ]
