# Generated by Django 6.0.4 on 2026-05-20 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_healthintakereport_html_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dashboard_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="diagnosis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="family_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="food_preference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="goal_weight_kg",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="goal_weight_lb",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height_cm",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height_feet",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height_inches",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="intake_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="intake_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="latest_chat_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="medications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pregnancy_cycle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminders",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="selected_problems",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="surgery_history",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight_kg",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight_lb",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.CreateModel(
            name="HealthMemoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("chat", "Chat"),
                            ("call", "Call"),
                            ("report", "Report"),
                            ("meal", "Meal"),
                            ("reminder", "Reminder"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("profile_fact", "Profile fact"),
                            ("intake_summary", "Intake summary"),
                            ("dashboard_update", "Dashboard update"),
                            ("reminder", "Reminder"),
                            ("report", "Report"),
                            ("safety", "Safety"),
                            ("meal", "Meal"),
                            ("mood", "Mood"),
                            ("sleep", "Sleep"),
                            ("medication", "Medication"),
                            ("symptom", "Symptom"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("content", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_memory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "category", "occurred_at"],
                        name="accounts_he_user_id_f2977d_idx",
                    ),
                    models.Index(
                        fields=["user", "source", "occurred_at"],
                        name="accounts_he_user_id_9724cc_idx",
                    ),
                ],
            },
        ),
    ]
