# Generated by Django 6.0.4 on 2026-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_age_userprofile_allergies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="safety_consent_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
