# Generated by Django 6.0.4 on 2026-05-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_safety_consent_accepted"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCorpusChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_uid", models.CharField(max_length=160, unique=True)),
                ("title", models.CharField(max_length=220)),
                (
                    "condition",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("condition", "Condition"),
                            ("symptom", "Symptom"),
                            ("diet", "Diet"),
                            ("exercise", "Exercise"),
                            ("safety", "Safety"),
                            ("follow_up", "Follow up"),
                            ("intake", "Intake"),
                            ("food", "Food"),
                            ("medication", "Medication"),
                            ("report", "Report"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=32,
                    ),
                ),
                ("text", models.TextField()),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("embedding_key", models.CharField(blank=True, max_length=220)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["condition", "section_type", "chunk_uid"],
            },
        ),
        migrations.CreateModel(
            name="MemorySchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_key", models.CharField(max_length=100, unique=True)),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("category", models.CharField(db_index=True, max_length=80)),
                ("json_schema", models.JSONField(default=dict)),
                ("extraction_prompt", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("expert_reviewed", "Expert reviewed"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["condition", "category", "schema_key"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_key", models.CharField(max_length=100, unique=True)),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("label", models.CharField(max_length=140)),
                ("unit", models.CharField(blank=True, max_length=40)),
                ("normal_range", models.CharField(blank=True, max_length=120)),
                ("high_risk_threshold", models.CharField(blank=True, max_length=120)),
                ("dashboard_mapping", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["condition", "metric_key"],
            },
        ),
        migrations.CreateModel(
            name="HealthProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol_id", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=220)),
                ("condition", models.CharField(db_index=True, max_length=120)),
                (
                    "protocol_type",
                    models.CharField(
                        choices=[
                            ("condition_care", "Condition care"),
                            ("diet_nutrition", "Diet and nutrition"),
                            ("indian_food_substitution", "Indian food substitution"),
                            ("exercise_fitness", "Exercise and fitness"),
                            ("symptom_risk_triage", "Symptom and risk triage"),
                            ("intake_question_flow", "Intake question flow"),
                            ("reminder_checkin", "Reminder and check-in"),
                            ("report_block", "Report block"),
                            ("emotional_coaching", "Emotional coaching"),
                            ("faq_safety_boundary", "FAQ, safety, boundary"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("rules", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("expert_reviewed", "Expert reviewed"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="accounts.healthprotocol",
                    ),
                ),
                (
                    "source_chunks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="protocols",
                        to="accounts.healthcorpuschunk",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "protocol_type", "protocol_id"],
            },
        ),
        migrations.CreateModel(
            name="FoodRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("food_name", models.CharField(db_index=True, max_length=140)),
                ("cuisine_context", models.CharField(blank=True, max_length=120)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("recommend", "Recommend"),
                            ("limit", "Limit"),
                            ("avoid", "Avoid"),
                            ("substitute", "Substitute"),
                            ("portion", "Portion"),
                            ("timing", "Timing"),
                        ],
                        max_length=24,
                    ),
                ),
                ("guidance", models.TextField()),
                ("reason", models.TextField(blank=True)),
                ("alternatives", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("safety_notes", models.TextField(blank=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("expert_reviewed", "Expert reviewed"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="food_rules",
                        to="accounts.healthprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "food_name", "rule_type"],
            },
        ),
        migrations.CreateModel(
            name="ConditionProtocolMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("applicability", models.TextField(blank=True)),
                ("contraindications", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_maps",
                        to="accounts.healthprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "priority"],
            },
        ),
        migrations.CreateModel(
            name="HealthSourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=260)),
                ("publisher", models.CharField(max_length=160)),
                ("url", models.URLField(max_length=700, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("guideline", "Guideline"),
                            ("pdf", "PDF"),
                            ("web_page", "Web page"),
                            ("journal", "Journal"),
                            ("dataset", "Dataset"),
                            ("internal", "Internal"),
                            ("other", "Other"),
                        ],
                        default="web_page",
                        max_length=32,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=40)),
                ("country_scope", models.CharField(blank=True, max_length=80)),
                ("license_note", models.CharField(blank=True, max_length=260)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["publisher", "title"],
                "indexes": [
                    models.Index(
                        fields=["publisher", "source_type"],
                        name="accounts_he_publish_7f484e_idx",
                    ),
                    models.Index(
                        fields=["language", "country_scope"],
                        name="accounts_he_languag_7caf69_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="healthcorpuschunk",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="accounts.healthsourcedocument",
            ),
        ),
        migrations.CreateModel(
            name="IntakeFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_id", models.CharField(max_length=80, unique=True)),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(max_length=180)),
                ("questions", models.JSONField(default=list)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("active", models.BooleanField(default=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("expert_reviewed", "Expert reviewed"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_flows",
                        to="accounts.healthprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "priority", "flow_id"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_level", models.CharField(blank=True, max_length=80)),
                ("note", models.TextField(blank=True)),
                ("quote", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="protocol_evidence",
                        to="accounts.healthcorpuschunk",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="accounts.healthprotocol",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocol_evidence",
                        to="accounts.healthsourcedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["protocol", "source"],
            },
        ),
        migrations.CreateModel(
            name="ReminderScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("trigger_type", models.CharField(db_index=True, max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("script", models.TextField()),
                ("schedule_hint", models.CharField(blank=True, max_length=120)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("call", "Call"),
                            ("push", "Push"),
                            ("report", "Report"),
                        ],
                        default="push",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_scripts",
                        to="accounts.healthprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "trigger_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="ReportBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("block_type", models.CharField(db_index=True, max_length=80)),
                ("title", models.CharField(max_length=180)),
                ("markdown_template", models.TextField()),
                ("required_metrics", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("expert_reviewed", "Expert reviewed"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_blocks",
                        to="accounts.healthprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "block_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="SafetyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(db_index=True, max_length=120)),
                ("symptom_pattern", models.CharField(max_length=220)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("self_care", "Self-care"),
                            ("soon", "Book appointment"),
                            ("urgent", "Urgent care"),
                            ("emergency", "Emergency"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("action", models.TextField()),
                ("escalation_text", models.TextField(blank=True)),
                ("contraindications", models.JSONField(blank=True, default=list)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("expert_reviewed", "Expert reviewed"),
                            ("deprecated", "Deprecated"),
                            ("replaced", "Replaced"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "protocol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_rules",
                        to="accounts.healthprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ["condition", "-severity", "symptom_pattern"],
            },
        ),
        migrations.AddIndex(
            model_name="healthprotocol",
            index=models.Index(
                fields=["condition", "protocol_type", "review_status"],
                name="accounts_he_conditi_69937c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthprotocol",
            index=models.Index(
                fields=["risk_level", "review_status"],
                name="accounts_he_risk_le_130d87_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="foodrule",
            index=models.Index(
                fields=["condition", "rule_type"], name="accounts_fo_conditi_e6a14c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodrule",
            index=models.Index(
                fields=["food_name", "rule_type"], name="accounts_fo_food_na_691557_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conditionprotocolmap",
            unique_together={("condition", "protocol")},
        ),
        migrations.AddIndex(
            model_name="healthcorpuschunk",
            index=models.Index(
                fields=["condition", "section_type"],
                name="accounts_he_conditi_b0e980_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthcorpuschunk",
            index=models.Index(
                fields=["source", "section_type"], name="accounts_he_source__aa0069_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="safetyrule",
            index=models.Index(
                fields=["condition", "severity"], name="accounts_sa_conditi_95ae26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="safetyrule",
            index=models.Index(
                fields=["review_status", "severity"],
                name="accounts_sa_review__519a55_idx",
            ),
        ),
    ]
