# Generated by Django 6.0.4 on 2026-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_healthcorpuschunk_memoryschema_outcomemetric_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="care_tasks",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chat_history",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="health_logs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="meal_analyses",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reports",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="safety_events",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="saved_reminders",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
