# Generated by Django 6.0.4 on 2026-05-20 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userprofile_care_tasks_userprofile_chat_history_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCareTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=140)),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("task_type", models.CharField(db_index=True, max_length=60)),
                ("title", models.CharField(max_length=180)),
                ("detail", models.TextField(blank=True)),
                ("time_label", models.CharField(blank=True, max_length=80)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                (
                    "last_completed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_task_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["time_label", "title"],
                "indexes": [
                    models.Index(
                        fields=["user", "task_type", "enabled"],
                        name="accounts_us_user_id_67c0b1_idx",
                    ),
                    models.Index(
                        fields=["user", "problem_name", "enabled"],
                        name="accounts_us_user_id_8d3d1b_idx",
                    ),
                ],
                "unique_together": {("user", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="UserChatMessageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=140)),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("role", models.CharField(db_index=True, max_length=24)),
                ("text", models.TextField()),
                ("is_error", models.BooleanField(default=False)),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_message_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "problem_name", "sent_at"],
                        name="accounts_us_user_id_283de5_idx",
                    ),
                    models.Index(
                        fields=["user", "role", "sent_at"],
                        name="accounts_us_user_id_e43b6b_idx",
                    ),
                ],
                "unique_together": {("user", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="UserHealthLogRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=140)),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("log_type", models.CharField(db_index=True, max_length=60)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("value", models.CharField(blank=True, max_length=120)),
                ("unit", models.CharField(blank=True, max_length=60)),
                ("note", models.TextField(blank=True)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_log_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "log_type", "recorded_at"],
                        name="accounts_us_user_id_6b7c35_idx",
                    ),
                    models.Index(
                        fields=["user", "problem_name", "recorded_at"],
                        name="accounts_us_user_id_ca5433_idx",
                    ),
                ],
                "unique_together": {("user", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="UserMealAnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=140)),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("meal_name", models.CharField(blank=True, max_length=180)),
                ("score", models.PositiveSmallIntegerField(db_index=True, default=0)),
                ("decision", models.CharField(blank=True, max_length=120)),
                ("calorie_range", models.CharField(blank=True, max_length=120)),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_analysis_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analyzed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "problem_name", "analyzed_at"],
                        name="accounts_us_user_id_2b7e06_idx",
                    ),
                    models.Index(
                        fields=["user", "score", "analyzed_at"],
                        name="accounts_us_user_id_ed310c_idx",
                    ),
                ],
                "unique_together": {("user", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="UserReminderRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=140)),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField(blank=True)),
                ("hour", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("minute", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["hour", "minute", "title"],
                "indexes": [
                    models.Index(
                        fields=["user", "enabled"],
                        name="accounts_us_user_id_2be255_idx",
                    ),
                    models.Index(
                        fields=["user", "problem_name"],
                        name="accounts_us_user_id_ff265b_idx",
                    ),
                ],
                "unique_together": {("user", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="UserSafetyEventRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=140)),
                (
                    "problem_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("source", models.CharField(blank=True, max_length=80)),
                ("severity", models.CharField(db_index=True, max_length=40)),
                ("rule_id", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("matched_text", models.TextField(blank=True)),
                ("action", models.TextField(blank=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_event_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "severity", "occurred_at"],
                        name="accounts_us_user_id_5d312e_idx",
                    ),
                    models.Index(
                        fields=["user", "problem_name", "occurred_at"],
                        name="accounts_us_user_id_5bf092_idx",
                    ),
                ],
                "unique_together": {("user", "external_id")},
            },
        ),
    ]
